### ISSUE TITLE
FreeVariablesVisitor no defined

### ISSUE THREAD

**Issue by ashoj** [nessos/GpuLinq#1]
Hi, Thank you for your interesting project.
Yesterday I downloaded the project and tried to compile it, but probably I am missing something, it says "FreeVariablesVisitor no defined"
Please let me know how can I resolve this.

Best 
Abbas

**Comment by palladin** [comment]
Hi Abbas,
You need to download also LinqOptimizer (dev branch) (https://github.com/nessos/LinqOptimizer).
In the near future we'll create a proper GpuLinq nuget package and reference the current nuget LinqOptimizer package.

Thanks for your interest!

**Comment by ashoj** [comment]
Thank you. I downloaded and referenced it. But it seems that it is not defined anywhere in linqOptimizer too.

Best

**Comment by palladin** [comment]
It is here https://github.com/nessos/LinqOptimizer/blob/dev/src/LinqOptimizer.Core/FreeVariablesVisitor.fs

**Comment by ashoj** [comment]
Thank your, compiled. This is a great idea and probably will be the easiest way to harness GPUs' power, but I noticed that the project is not released yet. Do you have a roadmap? How much functional is it now? which features are lacked or are going to be added?
Best

**Comment by palladin** [comment]
We are very close for our first nuget Package release, probably in a few weeks.
For supported features you can check our unit-tests and samples.
Currently we're working to be feature complete for our Mandlebrot sample.
The next step will be probably support for GpuStrings because GPUs are great accelerators for Big Data computing.

Again, thanks for your interest!
Nick
